"""Add users model

Revision ID: 1fa4c5aa01f1
Revises: 2be6b1c92260
Create Date: 2025-04-30 08:29:49.926513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.models.users import Gender, Role


# revision identifiers, used by Alembic.
revision: str = '1fa4c5aa01f1'
down_revision: Union[str, None] = '2be6b1c92260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_enum = sa.Enum(*[role.value for role in Role], name='role')
gender_enum = sa.Enum(*[gender.value for gender in Gender], name='gender')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column("users", sa.Column("role", user_enum, nullable=False))
    op.add_column("users", sa.Column("gender", gender_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    sa.Enum(name="role").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="gender").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
