"""Fix PostTag

Revision ID: 250d98b21d84
Revises: 6d49a61ac8a1
Create Date: 2025-05-04 19:06:01.156056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '250d98b21d84'
down_revision: Union[str, None] = '6d49a61ac8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_tags', sa.Column('tag_id', sa.UUID(), nullable=False))
    op.drop_constraint('post_tags_tag_name_fkey', 'post_tags', type_='foreignkey')
    op.create_foreign_key(None, 'post_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_column('post_tags', 'tag_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_tags', sa.Column('tag_name', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.create_foreign_key('post_tags_tag_name_fkey', 'post_tags', 'tags', ['tag_name'], ['id'], ondelete='CASCADE')
    op.drop_column('post_tags', 'tag_id')
    # ### end Alembic commands ###
